# Configuração do Cloudflare Tunnel para MCP Server
# Arquivo: cloudflare-tunnel-config.yml

tunnel: assistente-mcp-server
credentials-file: /home/thadeu/.cloudflared/assistente-mcp-server.json

ingress:
  # Rota para o servidor MCP HTTP
  - hostname: assistente-mcp.seu-dominio.com
    service: http://localhost:3001
    originRequest:
      httpHostHeader: localhost:3001
      
  # Rota padrão (obrigatória)
  - service: http_status:404

# Configurações de logging
loglevel: info

# Configurações de conectividade
retries: 3
grace-period: 30s
