services:
  app:
    build: .
    container_name: assistentev4
    restart: unless-stopped
    ports:
      - "7250:7250"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - DOCKER_ENV=true
    networks:
      - rede-compartilhada

networks:
  rede-compartilhada:
    external: true
    name: minha-rede-compartilhada
