version: '3.8'

# Docker Compose para desenvolvimento/teste do MCP Server
# Para produção com OpenAI, use o servidor stdio diretamente: node index.js

services:
  mcp-server-http:
    build: .
    container_name: assistente-mcp-server-http
    ports:
      - "${MCP_PORT:-3001}:${MCP_PORT:-3001}"
    environment:
      - NODE_ENV=development
      - MCP_PORT=${MCP_PORT:-3001}
      - MCP_LOGGING=true
      - LOG_LEVEL=debug
    env_file:
      - .env
    volumes:
      # Volume para logs
      - ../logs:/app/logs
      # Volume para arquivos temporários  
      - ../temp_audio:/app/temp_audio
      - ../temp_calendar:/app/temp_calendar
      # Volume para credenciais Google
      - ../google-credentials.json:/app/google-credentials.json:ro
      - ../google-oauth-desktop-credentials.json:/app/google-oauth-desktop-credentials.json:ro
      - ../google-token.json:/app/google-token.json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${MCP_PORT:-3001}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge

# NOTA: Para integração com OpenAI, use o servidor stdio:
# node /home/thadeu/assistentev4/mcp-server/index.js
